name: Deploy To Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy To Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Start Server
        run: npm run start &
        env:
          NODE_ENV: test
        # The "&" runs the server in the background

      - name: Wait for Server to Start
        run: npx wait-on http://localhost:3000
        # This waits until the server is ready before running tests

      - name: Run Cypress Tests
        run: npm run test

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Triggering Render deployment..."
          curl "$deploy_url"
          echo "Render deployment triggered."