name: Deploy To Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy To Render
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Triggering Render deployment..."
          curl "$deploy_url"
          echo "Render deployment triggered."