name: Checking Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Checking Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Start Server (Background)
        run: npm run start &
        env:
          NODE_ENV: test

      - name: Wait for Server to Start
        run: npx wait-on --timeout 30000 http://localhost:3000

      - name: Run Cypress Component Tests
        run: npm run test:component
        env:
          NODE_OPTIONS: "--loader ts-node/esm"
